theme: jekyll-theme-minimal
title: Jauzo Oy
description: IT Consulting Services
# logo: 
show_downloads: false
jekyll_analytics:
  Plausible:
    domain: 'jauzo.com'
    source: 'https://plausible.io/js/plausible.js'
